budget/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^$',
        views.home,
        name = 'home'
    ),
    url(
        r'^entry/list/$',
        views.entry_list,
        name = 'entry_list'
    ),
    url(
        r'^entry/(?P<entry_id>\d+)/$',
        views.entry_detail,
        name = 'entry_detail'
    ),
    url(
        r'^entry/(?P<entry_id>\d+)/edit/$',
        views.entry_edit,
        name = 'entry_edit'
    ),
    url(
        r'^entry/create/$',
        views.entry_create,
        name = 'entry_create'
    ),
    url(
        r'^category/create/$',
        views.category_create,
        name = 'category_create'
    ),
    url(
        r'^category/(?P<category_id>\d+)/$',
        views.category_detail,
        name = 'category_detail'
    ),
    url(
        r'^category/(?P<category_id>\d+)/edit/$',
        views.category_edit,
        name = 'category_edit'
    ),
    url(
        r'^category/list/$',
        views.category_list,
        name = 'category_list'
    ),
]

budgie/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from budgie import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^accounts/login/',
        views.user_login,
        name = 'user_login'
    ),

    url(r'^accounts/logout/',
        views.user_logout,
        name = 'user_logout'
    ),

    url(r'^$',
        views.index,
        name = 'index'
    ),

    url(r'^budget/', include('budget.urls')),
    url(r'^stats/', include('stats.urls')),
    url(r'^assistant/', include('assistant.urls')),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
]

stats/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^$',
        views.stats_home,
        name = 'stats_home'
    ),
]

budget/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.timezone import now


class Category(models.Model):
    '''
    The expense or income category
    '''
    def __str__(self):
        return self.name

    # The category name (required)
    name = models.CharField(
        max_length = settings.MAX_NAME_LENGTH,
        blank = False,
    )

    # A more detailed description of the category (not required)
    description = models.CharField(
        max_length = settings.MAX_DESCRIPTION_LENGTH,
        blank = True,
    )

    parent = models.ForeignKey(
        'Category',
        on_delete = models.CASCADE,
        blank=True,
        null=True,
    )

    # Every entry is owned by a user
    user = models.ForeignKey(
        User,
        on_delete = models.CASCADE
    )


class Entry(models.Model):
    '''
    A journal entry
    '''
    def __str__(self):
        return self.label

    # A string describing the entry
    label = models.CharField(
        max_length = settings.MAX_NAME_LENGTH,
        blank = False,
    )

    # The cost of the expense or the amount of income
    value = models.DecimalField(
        blank = False,
        default = 0.00,
        decimal_places = 2,
        max_digits = 20,
    )

    # The date of the entry
    date = models.DateField(
        blank = False,
    )

    # The date-time created, used for sorting
    date_created = models.DateTimeField(
        auto_now_add = True,
    )

    # Is the entry an expense or income
    INCOME = 'income'
    EXPENSE = 'expense'
    flow_type = models.CharField(
        choices = (
            (INCOME, 'Income'),
            (EXPENSE, 'Expense'),
        ),
        max_length = 50,
        default = 'expense',
    )

    # The category of the Entry (Required. User is encouraged to create an uncategorized category)
    category = models.ForeignKey(
        'Category',
        on_delete = models.CASCADE,
    )

    # A more detailed description of the Entry (not required)
    description = models.CharField(
        max_length = settings.MAX_DESCRIPTION_LENGTH,
        blank = True,
    )

    # Is the expense essential (required but not considered when processing income)
    essential = models.BooleanField(
        default = False,
    )

    # Every entry is owned by a user
    user = models.ForeignKey(
        User,
        on_delete = models.CASCADE
    )

budget/forms.py
from django import forms
from budget.models import Entry, Category
from functools import partial

DateInput = partial(forms.DateInput, {'class': 'datepicker'})

class EntryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(EntryForm, self).__init__(*args, **kwargs)
        self.fields['category'].choices = [(cat.id, cat) for cat in Category.objects.filter(user = user).order_by('name')]

    class Meta:
        model = Entry
        fields = '__all__'
        exclude = ('user', )
        widgets = {'date': DateInput(),}

def get_parent_choices_list(instance, user):
    categories = Category.objects.filter(user = user).order_by('name')
    if instance:
        categories = categories.exclude(id = instance.id)
    return [("", "--")] + [(cat.id, cat) for cat in categories]

class CategoryForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.fields['parent'].choices = get_parent_choices_list(kwargs.get('instance', None), user)

    class Meta:
        model = Category
        fields = '__all__'
        exclude = ('user', )

budget/views.py
import datetime
import json

from collections import OrderedDict

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from budget.models import Entry, Category
from budget.forms import EntryForm, CategoryForm

def get_total_value(entries):
    return sum([float(entry.value) for entry in entries])

def get_earliest_entry_date(entries):
    return min([entry.date for entry in entries])

def get_average_spent_over_period(entries, period):
    today = datetime.date.today()
    earliest_entry = get_earliest_entry_date(entries)
    days_since_first_entry = (today - earliest_entry).days
    segments = days_since_first_entry / period
    return get_total_value(entries) / segments

def filter_entries_to_period(entries, period):
    today = datetime.date.today()
    return entries.filter(date__gte = today - datetime.timedelta(days = period))

def get_value_over_period(entries, period):
    return get_total_value(filter_entries_to_period(entries, period))

def get_spending_summary(entries):
    entries = entries.filter(flow_type = Entry.EXPENSE)
    return {
        'week': get_value_over_period(entries, 7),
        'average_week': get_average_spent_over_period(entries, 7),
        'month': get_value_over_period(entries, 30),
        'average_month': get_average_spent_over_period(entries, 30),
    }

def get_income_summary(entries):
    entries = entries.filter(flow_type = Entry.INCOME)
    return {
        'year': get_value_over_period(entries, 360),
        'month': get_value_over_period(entries, 30),
        'week': get_value_over_period(entries, 7),
        'years_monthly_budget': get_value_over_period(entries, 365) / 12,
        'months_weekly_budget': get_value_over_period(entries, 30) / (30/7),
    }

def get_user_entries(user):
    return Entry.objects.filter(user=user)

def get_entry_occurances(entries):
    return {entry.label: entries.filter(label=entry.label).count() for entry in entries}

def get_sorted_entry_occurances(entries):
    return sorted(get_entry_occurances(entries).items(), key=lambda x: x[1], reverse=True)

def get_most_frequent_entries(entries, num):
    '''
    Returns a list of the most recent entry for each of the most common entry labels
    '''
    return [entries.filter(label = entry[0]).latest('id') for entry in get_sorted_entry_occurances(entries)[:num]]

def get_budget_status(spending_summary, income_summary):
    '''
    Green: you're under your budget and under your average.
    Blue: You're under your budget but not your average.
    Orange: your within 25% of your budget.
    Red: you're over 25% of your budget
    '''
    status = {
        'week': {'colour': '#b00', 'description': 'Over'},
        'month': {'colour': '#b00', 'description': 'Over'},
    }

    for period in status.keys():
        spent = spending_summary[period]
        budget_key = 'years_monthly_budget' if period == 'month' else 'months_weekly_budget'
        budget = income_summary[budget_key]
        average = spending_summary['average_{}'.format(period)]
        if spent < budget:
            if spent < average:
                status[period] = {'colour': '#0b0', 'description': 'Good'}
            else:
                status[period] = {'colour': '#00b', 'description': 'Ok'}
        if spent > budget * 0.75 and spent < budget * 1.25:
            status[period] = {'colour': '#E59400', 'description': 'Close'}
    return status

def get_entry_json_data(entry):
    return json.dumps({
        'label': entry.label,
        'value': float(entry.value),
        'flow_type': entry.flow_type,
        'category': entry.category.id,
        'essential': entry.essential,
        'description': entry.description,
    })

@login_required
def home(request):
    template = 'index.html'
    entries = Entry.objects.filter(user = request.user)
    spending_summary = get_spending_summary(entries)
    income_summary = get_income_summary(entries)
    context = {
        'spendings': spending_summary,
        'income': income_summary,
        'budget_status': get_budget_status(spending_summary, income_summary),
    }
    return render(request, template, context)

@login_required
def entry_list(request):
    template = 'entry_list.html'
    context = {}
    if request.POST:
        entry_ids = [int(entry_id) for entry_id, state in dict(request.POST).items() if state == ['on']]
        Entry.objects.filter(id__in = entry_ids).delete()
        context['success'] = True
    context['entries'] = Entry.objects.filter(user = request.user).order_by('-date', '-date_created')
    return render(request, template, context)

@login_required
def entry_detail(request, entry_id):
    template = 'entry_detail.html'
    entry = Entry.objects.get(id = entry_id)
    context = {
        'entry': entry,
    }
    return render(request, template, context)

@login_required
def entry_edit(request, entry_id):
    template = 'entry_edit.html'
    entry = Entry.objects.get(id = entry_id)
    context = {
        'entry': entry,
    }

    if request.method == 'POST':
        form = EntryForm(request.POST, instance = entry, user = request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = EntryForm(user = request.user, instance = entry)

    context['form'] = form
    return render(request, template, context)

@login_required
def entry_create(request):
    template = 'entry_edit.html'
    context = {}

    if request.method == 'POST':
        form = EntryForm(request.POST, user = request.user)
        if form.is_valid():
            entry = form.save(commit = False)
            entry.user = request.user
            entry.save()
            return redirect('entry_detail', entry_id = entry.id)
    else:
        context['frequent_entries'] = [(entry, get_entry_json_data(entry)) for entry in
                get_most_frequent_entries(
                    filter_entries_to_period(
                        get_user_entries(request.user), 60), 10)] # most frequent 10 in past 60 days # TODO make this a setting
        form = EntryForm(user = request.user)

    context['form'] = form
    context['has_error'] = not form.errors == {}

    return render(request, template, context)

@login_required
def category_list(request):
    template = 'category_list.html'
    context = {}
    if request.POST:
        category_ids = [int(category_id) for category_id, state in dict(request.POST).items() if state == ['on']]
        Category.objects.filter(id__in = category_ids).delete()
        context['success'] = True
    context['categories'] = Category.objects.filter(user = request.user).order_by('name')
    return render(request, template, context)

def get_category_summary(category):
    entries = Entry.objects.filter(category = category, flow_type=Entry.EXPENSE)
    today = datetime.date.today()
    summary = {
        'forever': get_total_value(entries),
        'week': get_value_over_period(entries, 7),
        'month': get_value_over_period(entries, 30),
        'year': get_value_over_period(entries, 365),
    }
    summary['average_week_over_month'] = summary['month'] / (30 / 7)
    summary['average_week_over_year'] = summary['year'] / (365 / 7)
    summary['average_month_over_year'] = summary['year'] / 12
    return summary

@login_required
def category_detail(request, category_id):
    template = 'category_detail.html'
    category = Category.objects.get(id = category_id)
    context = {
        'category': category,
        'spendings': get_category_summary(category),
    }
    return render(request, template, context)

@login_required
def category_edit(request, category_id):
    template = 'category_edit.html'
    category = Category.objects.get(id = category_id)
    context = {
        'category': category
    }

    if request.method == 'POST':
        form = CategoryForm(request.POST, instance = category, user = request.user)
        if form.is_valid():
            form.save()
            context['success'] = True
    else:
        form = CategoryForm(instance = category, user = request.user)

    context['form'] = form
    return render(request, template, context)

@login_required
def category_create(request):
    template = 'category_edit.html'
    context = {}

    if request.method == 'POST':
        form = CategoryForm(request.POST, user = request.user)
        if form.is_valid():
            category = form.save(commit = False)
            category.user = request.user
            category.save()
            return redirect('category_detail', category_id = category.id)
    else:
        form = CategoryForm(user = request.user)

    context['form'] = form
    context['has_error'] = not form.errors == {}

    return render(request, template, context)

budget/templates/category_detail.html
{% extends "base.html" %}

{% block heading %}
  {% block title %}
    Category: {{ category }}
  {% endblock %}
{% endblock %}

{% block content %}
  <a class="button" href="{% url 'category_edit' category.id %}">Edit Category</a>
  <h2>{{ category }} details</h4>
  <table class="detail">
    <thead>
      <tr>
        <th>Attribute</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Name</td>
        <td>{{ category.name }}</td>
      </tr>
      <tr>
        <td>Description</td>
        <td>{{ category.description }}</td>
      </tr>
      <tr>
        <td>Parent</td>
        <td>{{ category.parent }}</td>
      </tr>
    </tbody>
  </table>

  <h2>{{ category }} expenditure</h4>
  <table class="detail">
    <thead>
      <tr>
        <th>Time Period</th>
        <th>Amount Spent</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Forever</td>
        <td>${{ spendings.forever | floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Week</td>
        <td>${{ spendings.week | floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Month</td>
        <td>${{ spendings.month | floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Year</td>
        <td>${{ spendings.year | floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Avg. week over month.</td>
        <td>${{ spendings.average_week_over_month  | floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Avg. week over year.</td>
        <td>${{ spendings.average_week_over_year | floatformat:2 }}</td>
      </tr>
      <tr>
        <td>Avg. month over year.</td>
        <td>${{ spendings.average_month_over_year | floatformat:2 }}</td>
      </tr>
    </tbody>
  </table>
{% endblock %}

budget/templates/category_edit.html
{% extends "base.html" %}

{% block heading %}
  {% block title %}
    {% if entry %}
      Editing: {{ entry }}
    {% else %}
      Create Category
    {% endif %}
  {% endblock %}
{% endblock %}

{% block content %}
  {% include "form.html" %}
{% endblock %}

budget/templates/category_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block heading %}
  {% block title %}
    Categories
  {% endblock %}
{% endblock %}

{% block extrahead %}
  <script src="{% static "js/budgie/list_views.js" %}"></script>
{% endblock %}

{% block content %}
  <form class="list_form" method="POST">
    {% csrf_token %}
    {% if success %}
      <p id="success_message" class="success">Categories have successfully been deleted.</p>
    {% endif %}
    <button class="button" id="delete_btn" type="submit">Delete Selected</button>
    <a class="button" href="{% url 'category_create' %}">New Category</a>
    <table class="list">
      <thead>
        <tr>
          <th>Select</th>
          <th>Name</th>
          <th>Description</th>
          <th>Parent</th>
        </tr>
      </thead>
      <tbody>
        {% if categories %}
          {% for category in categories %}
            <tr>
              <td><input type="checkbox" name="{{ category.id }}"/></td>
              <td><a href={% url 'category_detail' category.id %}>{{ category.name }}</a></td>
              <td>{{ category.description }}</td>
              <td>{{ category.parent }}</td>
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td style="text-align: center;" colspan="3">There are no categories to display.</td>
          </tr>
        {% endif %}
      </tbody>
    </table>
  </form>
{% endblock %}

budget/templates/entry_detail.html
{% extends "base.html" %}

{% block heading %}
  {% block title %}
    Entry: {{ entry.label }}
  {% endblock %}
{% endblock %}

{% block content %}
  <table class="detail">
    <thead>
      <tr>
        <th>Attribute</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Label</td>
        <td>{{ entry.label }}</td>
      </tr>
      <tr>
        <td>Value</td>
        <td>${{ entry.value }}</td>
      </tr>
      <tr>
        <td>Category</td>
        <td><a href={% url 'category_detail' entry.category.id %}>{{ entry.category }}</a></td>
      </tr>
      <tr>
        <td>Type</td>
        <td>{{ entry.flow_type }}</td>
      </tr>
      <tr>
        <td>Description</td>
        <td>{{ entry.description }}</td>
      </tr>
      <tr>
        <td>Date</td>
        <td>{{ entry.date }}</td>
      </tr>
      <tr>
        <td>Essential</td>
        <td>{{ entry.essential }}</td>
      </tr>
    </tbody>
  </table>
  <a class="button" href="{% url 'entry_edit' entry.id %}">Edit</a>
{% endblock %}

budget/templates/entry_edit.html
{% extends "base.html" %}

{% block heading %}
  {% block title %}
    {% if entry %}
      Editing: {{ entry }}
    {% else %}
      Create Entry
    {% endif %}
  {% endblock %}
{% endblock %}

{% block content %}
  <table class="markup-table">
    <tr>
      <td>
        {% include "form.html" %}
      </td>

      <td valign="top" style="padding-left: 80px">
        {% if frequent_entries %}
          <div>
          <h3>Apply a Template</h3>
          {% for entry, json in frequent_entries %}
            <div>
              <p name="template-entry">{{entry.label}}</p>
              <div hidden="hidden" id="entry-data-{{entry.label}}">{{ json }}</div>
            </div>
          {% endfor %}
          </div>
        {% endif %}
      </td>
    </tr>
  </table>

  <script>
    // Apply templates to the form
    $(document).ready(function(){
      $('[name="template-entry"]').click(function(e){
        var p_tag = e.originalEvent.originalTarget;
        var entry_data = JSON.parse(p_tag.parentElement.lastElementChild.firstChild.data);
        $.each(entry_data, function(field, value){
          var field = $('#id_' + field);
          if (field.is(':checkbox')){
            field.prop("checked", value);
          }else{
            field.val(value);
          }
        });
      });
    });
  </script>

  {% if not entry %}
    <script>
      // Prevent prifilling with 0 so it doesn't have to be cleared
      $('#id_value').val('');
    </script>
  {% endif %}

    <script>
        // Init Datepicker
      $(document).ready(function() {
        var datepicker = $('.datepicker');
        datepicker.datepicker();

        {% if not entry %}
          // Fill date with todays date
          var today = new Date();
          var day = today.getDate();
          var month = today.getMonth()+1;
          var year = today.getFullYear();
          datepicker.val(month + '/' + day + '/' + year);
        {% endif %}
      });
    </script>
{% endblock %}

budget/templates/entry_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block heading %}
  {% block title %}
    Entry Listing
  {% endblock %}
{% endblock %}

{% block extrahead %}
  <script src="{% static "js/budgie/list_views.js" %}"></script>
{% endblock %}

{% block content %}
  <form class="list_form" method="POST">
    {% csrf_token %}
    {% if success %}
      <p id="success_message" class="success">Entries have successfully been deleted.</p>
    {% endif %}
    <button class="button" id="delete_btn" type="submit">Delete Selected</button>
    <table class="list">
      <thead>
        <tr>
          <th>Select</th>
          <th>Label</th>
          <th>Amount</th>
          <th>Category</th>
          <th>Type</th>
          <th>Description</th>
          <th>Date</th>
          <th>Essential</th>
        </tr>
      </thead>
      <tbody>
        {% if entries %}
          {% for entry in entries %}
            <tr>
              <td><input type="checkbox" name="{{ entry.id }}"/></td>
              <td><a href={% url 'entry_detail' entry.id %}>{{ entry.label }}</a></td>
              <td>${{ entry.value }}</td>
              <td><a href={% url 'category_detail' entry.category.id %}>{{ entry.category }}</a></td>
              <td>{{ entry.flow_type }}</td>
              <td>{{ entry.description }}</td>
              <td>{{ entry.date }}</td>
              <td>{{ entry.essential }}</td>
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td style="text-align: center;" colspan="8">There are no entries to display.</td>
          </tr>
        {% endif %}
      </tbody>
    </table>
  </form>

{% endblock %}

budget/templates/form.html
<form method="POST">
  {% csrf_token %}
  {% if success %}
    <p class="success">The form has successfully been saved.</p>
  {% endif %}
  {% if has_error %}
    <p class="error">Please address the errors below.</p>
  {% endif %}
  <table>
    {% for field in form %}
      <tr>
        <td class="label">{{ field.label_tag }}</td>
        <td class="field">{{ field }}</td>
      </tr>
      {% if field.errors %}
        <tr>
          <td colspan="100" class="error">{{ field.errors }}</td>
        </tr>
      {% endif %}
    {% endfor %}
  </table>
  <button type="submit">Submit</button>
</form>

budget/templates/index.html
{% extends "base.html" %}

{% block heading %}
  {% block title %}
    Home
  {% endblock %}
{% endblock %}

{% block content %}
  <div class="status_box">
    This Week
    <div class="status_circle" style="background: {{ budget_status.week.colour }};">
      {{ budget_status.week.description }}
    </div>
  </div>
  <div class="status_box">
    This Month
    <div class="status_circle" style="background: {{ budget_status.month.colour }};">
      {{ budget_status.month.description }}
    </div>
  </div>

  <h3>Your Budget</h3>
  <p>This years monthly budget: <b>${{ income.years_monthly_budget | floatformat:2 }}</b></p>
  <p>This months weekly budget: <b>${{ income.months_weekly_budget | floatformat:2 }}</b></p>

  <hr>

  <h3>Your Spending Summary</h3>
  <p>
    In the past week you spent
    <b>${{ spendings.week | floatformat:2 }}</b>
    compared to your average of
    <b>${{ spendings.average_week | floatformat:2 }}</b>
    and your budget of
    <b>${{ income.months_weekly_budget | floatformat:2 }}</b>.
    {% if spendings.week < spendings.average_week %}
      Nice saving!
    {% else %}
      That's higher than average
    {% endif %}
    and
    {% if spendings.week < income.months_weekly_budget %}
      you're under budget!
    {% else %}
      that's above your budget.
    {% endif %}
  </p>

  <p>
    In the past month you spent
    <b>${{ spendings.month | floatformat:2 }}</b>
    compared to your average of
    <b>${{ spendings.average_month | floatformat:2 }}</b>
    and your budget of
    <b>${{ income.years_monthly_budget | floatformat:2 }}</b>.
  </p>

  <hr>

  <h3>Your Income Summary</h3>
  <p>Income this year: <b>${{ income.year | floatformat:2 }}</b></p>
  <p>Income this month: <b>${{ income.month | floatformat:2 }}</b></p>

{% endblock %}